# Generated by Django 6.0.4 on 2026-05-06 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Рассылка отправлена'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author'], name='announcemen_author__0e981a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category'], name='announcemen_categor_9fb50c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['announcement'], name='announcemen_announc_58a593_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['author'], name='announcemen_author__b1b7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['is_accepted'], name='announcemen_is_acce_3317aa_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created_at'], name='announcemen_created_a8e392_idx'),
        ),
    ]
