# Generated by Django 6.0.4 on 2026-05-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_response_user_alter_response_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
