# Generated by Django 6.0.4 on 2026-05-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_response_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcement_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='announcements.announcement')),
            ],
        ),
    ]
